### PR TITLE
Addresses issue #301

### LINKED ISSUE #301: Fix breaking tests
After landing #265, we're now failing here:

RoleTooltipRequiresDescribedBy - a tooltip without an ID doesn't cause an exception...ERROR
>> Message: Running roleTooltipRequiresDescribedby threw an exception: 'undefined' is not a function (evaluating 'configuration.getSeverity(auditRule.name)')
>> at file:///home/travis/build/GoogleChrome/accessibility-developer-tools/test/qunit.js:418
RoleTooltipRequiresDescribedBy - role tooltip with a corresponding describedby of a missing element id should fail...ERROR
>> Message: Died on test #1: 'undefined' is not a function (evaluating 'configuration.getSeverity(auditRule.name)')
>> at file:///home/travis/build/GoogleChrome/accessibility-developer-tools/src/js/AuditRule.js:200

### PR DESCRIPTION
**Pull request by ricksbrown**
Closes #301

### CODE REVIEW

**Comment by ricksbrown** [comment]
@addyosmani This fixes those broken unit tests you refer to in #301

**Comment by addyosmani** [comment]
@ricksbrown You're the best 🎉 Thanks for the fixes to those tests!
